parameters:
  - name: pipelineResource
    type: string
    default: ''
  - name: pipelineSource
    type: string
    default: ''
  - name: artifactName
    type: string
    default: 'drop'
  - name: azureSubscription
    type: string
    default: ''
  - name: functionAppName
    type: string
    default: ''
  - name: environmentName
    type: string
    default: 'Platform-Dev'
  - name: displayName
    type: string
    default: 'Deploy Function App'
  - name: poolName
    type: string
    default: 'aidea-self-hosted-agents'

stages:
  - stage: Deploy
    displayName: 'Deploy to ${{ parameters.environmentName }}'
    jobs:
      - deployment: DeployFunctionApp
        displayName: ${{ parameters.displayName }}
        environment: ${{ parameters.environmentName }}
        pool:
          name: ${{ parameters.poolName }}
        strategy:
          runOnce:
            deploy:
              steps:
                - download: CI
                  artifact: ${{ parameters.artifactName }}
                  displayName: 'Download CI Artifact'

                - task: AzureFunctionApp@2
                  displayName: 'Deploy to ${{ parameters.functionAppName }}'
                  inputs:
                    azureSubscription: '${{ parameters.azureSubscription }}'
                    appType: 'functionApp'
                    appName: '${{ parameters.functionAppName }}'
                    package: '$(Pipeline.Workspace)/CI/${{ parameters.artifactName }}/${{ parameters.functionAppName }}'
                    deploymentMethod: 'auto'
