parameters:
  - name: pipelineResource
    type: string
    default: ''
  - name: pipelineSource
    type: string
    default: ''
  - name: artifactName
    type: string
    default: 'drop'
  - name: azureSubscription
    type: string
    default: ''
  - name: appName
    type: string
    default: ''
  - name: environmentName
    type: string
    default: 'Platform-Dev'
  - name: displayName
    type: string
    default: 'Deploy App Service'
  - name: poolName
    type: string
    default: 'aidea-self-hosted-agents'

stages:
  - stage: Deploy
    displayName: 'Deploy to ${{ parameters.environmentName }}'
    jobs:
      - deployment: DeployAppService
        displayName: ${{ parameters.displayName }}
        environment: ${{ parameters.environmentName }}
        pool:
          name: ${{ parameters.poolName }}
        strategy:
          runOnce:
            deploy:
              steps:
                - download: CI
                  artifact: ${{ parameters.artifactName }}
                  displayName: 'Download CI Artifact'

                - task: AzureRmWebAppDeployment@5
                  displayName: 'Deploy to ${{ parameters.appName }}'
                  inputs:
                    azureSubscription: '${{ parameters.azureSubscription }}'
                    appType: 'webApp'
                    WebAppName: '${{ parameters.appName }}'
                    package: '$(Pipeline.Workspace)/CI/${{ parameters.artifactName }}/${{ parameters.appName }}'
                    deploymentMethod: 'auto'
